### ISSUE TITLE
Finalize and publish the package to NPM

### ISSUE THREAD

**Issue by simoneb** [nearform/mercurius-dynamic-schema#50]
This project is nearly done, we should publish it to NPM. Check out the outstanding issues, sync with @brainrepo to make sure all the essential bits are covered, then publish to NPM.

**Comment by ekynoxe** [comment]
[Version 1.0.4](https://www.npmjs.com/package/mercurius-dynamic-schema) released to NPM

**Comment by simoneb** [comment]
@ekynoxe don't move issues manually in the board, close them and they'll be moved automatically
