### ISSUE TITLE
Write a blog post when the package is released

### ISSUE THREAD

**Issue by simoneb** [nearform/mercurius-dynamic-schema#51]
We built this package to provide and off the shelf solution for dynamic schema. We have described how they work in https://github.com/mercurius-js/mercurius/pull/979/files, which is part of the mercurius documentation.

Once the package is published, as per #50 , we should write a blog post describing what the package does and how, and we can include information from the docs as per the PR above.

**Comment by alfonsograziano** [comment]
Here the [blog post](https://www.notion.so/nearform/Introducing-Mercurius-Dynamic-Schema-800802e1be0d4429926d4c754354cdc5) draft
